config/routes.rb
Rails.application.routes.draw do

  resources :events do
    resources :participants do
      member do
        post :add_guest
      end
    end
  end

  root :to => 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :participants
  accepts_nested_attributes_for :participants, allow_destroy: true
  def total_participants
    total = self.participants.count
    self.participants.each do |participant|
      total += participant.guests
    end
    return total
  end
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  belongs_to :events
  accepts_nested_attributes_for :events, allow_destroy: true

  def popularity_label
    if guests < 2
      ""
    elsif guests < 5
    "Friendly"
    elsif guests < 10
      "Popular"
    elsif guests < 25
      "Social Butterfly"
    else
      "Pop Icon"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end
  def show
    @event = Event.find(params[:id])

  end
  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to events_url
    else
      render action: "new"
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update_attributes(event_params)
      redirect_to events_path
    else
      render action: "edit"
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_url
  end
  private
    def event_params
      params.require(:event).permit(:name, :description, :location, :date)
    end

end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  def create
    @event = Event.find(params[:event_id])
    @participant = @event.participants.new(participant_params)
    if @participant.save
      redirect_to event_url (@event)
    else
      redirect_to event_url (@event)
    end
  end

  def add_guest
    @event = Event.find(params[:event_id])
    @participant = Participant.find(params[:id])
    @participant.guests += 1
    @participant.save
    redirect_to event_url(@event)
  end

  private
    def participant_params
      params.require(:participant).permit(:name, :guests)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/events/edit.html.erb
<h2>Edit <%= @event.name %></h2>

<%= form_for @event do |form| %>
  <div>
    <%= form.label :name %><br />
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :location %><br />
    <%= form.text_field :location %>
  </div>

  <p><%= form.submit %></p>
<% end %>

app/views/events/index.html.erb
<h2>Events</h2>


<div class="hero-unit">
  <h1>Event Tracker</h1>
  <p>Planning an event? Track the participants here!</p>
  <p><%= link_to "Create New Event", new_event_url, :class => "brn btn-primary btn-large" %></p>
</div>

<table class="table table-striped">
  <thead>
    <th>Event</th>
    <th>Date</th>
    <th>Total Participants</th>
    <th>Actions</th>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
          <td>
            <%= link_to event.name, event_path(event) %> - <%= event.description %><br />
            <%= event.location %>
          </td>
          
          <td><%= event.date.to_formatted_s(:long) %></td>
          <td><%= event.total_participants %></td>
          <td>
            <%= link_to "Edit" , edit_event_path(event), :class => "brn btn-small btn-warning" %>
            <%= link_to 'Destroy', event,  :class => "brn btn-small btn-danger",  method: :delete, data: { confirm: 'Are you sure?'} %>
          </td>
        </tr>
        <% end %>
  </tbody>
</table>

app/views/events/new.html.erb
<h2>Create New Event</h2>
<%= form_for @event do |form| %>
  <div>
    <%= form.label :name %><br />
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %><br />
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :location %><br />
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :date %><br />
    <%= form.text_field :date %>
  </div>

  <p><%= form.submit %></p>
<% end %>

app/views/events/show.html.erb
  <h2 class="page-header"><%= @event.name %> <small> <a href="/">Back to Event Hub</a></small></h2>


<h3><%= @event.description %></h3>
<p><%= @event.location %></p>
<p><%= @event.date.to_formatted_s(:long) %></p>
<h3>Participants</h3>
<ul>
  <% @event.participants.each do |single_participant| %>
    <li><strong><%= single_participant.popularity_label + " " %></strong><%= single_participant.name %> is bringing <%= single_participant.guests %> guests<br />
      Bringing a guest? <%= button_to "Guest +1", add_guest_event_participant_path(@event.id, single_participant.id), :class => "brn btn-info " %>
    </li>
  <% end %>
</ul>

<h2>Add Participant</h2>

<%= form_for [@event, @event.participants.new] do |form| %>
  	<div class="form-group">
	  <%= form.text_field :name %>
	  <%= form.submit %>
	</div>
<% end %>

<h2>Add Date to Event</h2>
<%= form_for @event do |form| %>
	<div class="form-group">
		<%= form.text_field :date %>
	  	<%= form.submit %>
	 </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EventTracker</title>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>
</body>
</html>